steps:
# שלב 1: בנה את "קופסת הקוד" (Docker Image)
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'me-west1-docker.pkg.dev/whatsapp-calendar-bot-468708/whatsapp-bot-repo/calendar-bot:latest'
    - '.'
  id: 'Build'

# שלב 2: העלה את הקופסה למחסן
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'me-west1-docker.pkg.dev/whatsapp-calendar-bot-468708/whatsapp-bot-repo/calendar-bot:latest'
  id: 'Push'

# שלב 3: פרוס את הגרסה החדשה ל-Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'whatsapp-bot-service' # ודא שזהו שם השירות שלך ב-Cloud Run
    - '--image'
    - 'me-west1-docker.pkg.dev/whatsapp-calendar-bot-468708/whatsapp-bot-repo/calendar-bot:latest'
    - '--region'
    - 'me-west1' # <-- כאן התיקון!
    - '--quiet'
  id: 'Deploy'

options:
  logging: CLOUD_LOGGING_ONLY

